### ISSUE TITLE
chatterbox-service engineering

### ISSUE THREAD

**Issue by alphaolomi** [iam-kevin/go-chatterbox-service#1]
- Framework:?
- Orm:?
- Transport: Rest/Websockets
- X:?

**Comment by iam-kevin** [comment]
Trying to go as light as possible when building the service.

Currently:
- Using this for route handling (especially for the query params) https://github.com/gorilla/mux 
- Using https://github.com/gorilla/websocket for websockets
- No ORM (raw sql is the goal)
- ... will populate more details on the README
